### ISSUE TITLE
long silent tails

### ISSUE THREAD

**Issue by rwmitchell** [teddywing/auditory.vim#2]
I realize this is an old project. Curious as to why the sound bytes, such as Copy.wav, have such long dead time after the sound?  It would seem getting rid of any dead air would be more efficient.

**Comment by teddywing** [comment]
I’m afraid I don’t know the answer to that question. @SpencerBateman composed virtually all of the audio in the project. Perhaps he recalls.

We originally made this during a 24 hour hackathon, so I don’t imagine there was much time to refine things.

**Comment by SpencerBateman** [comment]
See Pull Request

**Comment by teddywing** [comment]
This is fixed by Spencer’s changes in #3. Thanks for your interest!
